#!/usr/bin/env ruby
require 'bundler'

Bundler.require

TM_PATH = File.expand_path(File.join(__FILE__, "..") )

require "#{TM_PATH}/lib/task"
require "#{TM_PATH}/lib/command"


# Notre code commence ici
Task.load "#{TM_PATH}/conf/tasks.json"

Command::Action.new('add', ':contenu (options...)', 'Crée une nouvelle tache.') do |arguments|
	Task.add(arguments)
end.register!

Command::TaskAction.new('del', '', 'Supprime une tache') do |task, args|
	Task.delete task.id
end.register!

#Command.register 'del', ':id', 'Supprime une tache' do |args|
#	Task.delete args.shift.to_i
#end
#
#Command.register 'mod', ':id (options...)', 'Modifie une tache' do |args|
#	puts "TODO"
#end
#
#Command.register 'list', ':filtre', 'Liste les taches' do |args|
#	Task.display
#end

Command.launch!

#parser_commande(command)
Task.display
Task.save "#{TM_PATH}/conf/tasks.json"