#!/usr/bin/env ruby

# Task
# id, content, flags, is_done
#
# afficher
# done
class Task


	OPTIONS_DEFAULT = {
		flags: [],
		date: nil
	}

	# Retourne une tache
	def self.add params
		contenu = params.shift
		id = @tableau_taches.map(&:id).max+1

		new_task = Task.new id, contenu

		params.each do |argument|
			champ, valeur = argument.split(':')

			if champ == "flags"
				new_task.flags = value.split(',')
			else
				raise "Parametre incorrect: #{champ}"
			end
		end

		@tableau_taches << new_task
	end

	def self.delete id
		@tableau_taches.reject!{ |tache| tache.id==id }
	end

	def self.display
		puts "*****TASKMAN*****"
		puts "LISTE DES TACHES "

		@tableau_taches.each(&:display)
	end

	attr_accessor :id, :content, :flags
	attr_reader :is_done

	def initialize id, content, opts={}
		opts = OPTIONS_DEFAULT.merge(opts)

		@id = id
		@content = content
		@flags = opts[:flags]
		@is_done = false
	end

	def display
		puts "[#{ @is_done ? "X" : " " }] #{@id} - #{@content} (#{@flags.join(",")})"
	end

	def done
		@is_done = true
	end

	@tableau_taches = [
		Task.new(0, "Améliorer taskman", flags:%w(important urgent ))
	]
end

module Command
	@commands = {}

	def self.register command, arguments, description, &block
		@commands[command] = {
			keyword: command,
			arguments: arguments,
			description: description,
			block: block
		}
	end


	def self.launch!
		command = ARGV.shift

		is_executed = false

		@commands.each do |k, v|
			if k == command
				is_executed = true
				v[:block].call(ARGV)
			end
		end

		unless is_executed
			display_help
		end
	end

	def self.display_help
		puts "taskman [commande] [contenu|id] [options...]"
		puts "--------------------------------------------"
		@commands.each do |k, v|
			puts "#{v[:keyword]} #{v[:arguments]}\t * #{v[:description]}"
		end
	end

end


Command.register('add', ':contenu (options...)', 'Crée une nouvelle tache.') do |arguments|
	Task.add(arguments)
end

Command.register 'del', ':id', 'Supprime une tache' do |args|
	Task.delete args.shift.to_i
end

Command.register 'mod', ':id (options...)', 'Modifie une tache' do |args|
	puts "TODO"
end

Command.register 'list', ':filtre', 'Liste les taches' do |args|
	Task.display
end

Command.register 'clear', '', 'Supprime toute les taches' do |args|
	#A FAIRE: Supprimer toute les taches.
end

Command.launch!

#parser_commande(command)
Task.display